// TODO: why not use enum?
export const CONTROL_SCHEME_NAME_IS_NOT_UNIQUE = 'CONTROL_SCHEME_NAME_IS_NOT_UNIQUE';
export const VALUE_IS_NOT_IN_ENUM = 'VALUE_IS_NOT_IN_ENUM';
export const VALUE_IS_NOT_BOOLEAN = 'VALUE_IS_NOT_BOOLEAN';
export const VALUE_IS_ZERO = 'VALUE_IS_ZERO';
