export const ROUTE_SECTIONS = {
    root: '',
    controllers: 'controllers',
    hubs: 'hubs',
    controlSchemes: 'control-schemes',
    binding: 'binding',
    bindingCreate: 'binding-create',
    portEdit: 'port',
    hubEdit: 'edit',
    controlSchemeCreate: 'create',
    about: 'about',
    settings: 'settings',
    help: 'help',
    steamDeckInstallationManual: 'steam-deck',
} as const;
