import { RouterState } from '@ngrx/router-store';

import { IState } from './i-state';
import {
    ATTACHED_IOS_INITIAL_STATE,
    ATTACHED_IO_MODES_INITIAL_STATE,
    ATTACHED_IO_PORT_MODE_INFO_INITIAL_STATE,
    ATTACHED_IO_PROPS_INITIAL_STATE,
    BLUETOOTH_AVAILABILITY_INITIAL_STATE,
    CONTROLLERS_INITIAL_STATE,
    CONTROLLER_INPUT_INITIAL_STATE,
    CONTROLLER_SETTINGS_INITIAL_STATE,
    CONTROL_SCHEMES_INITIAL_STATE,
    HUBS_INITIAL_STATE,
    HUB_EDIT_FORM_ACTIVE_SAVES_INITIAL_STATE,
    HUB_PORT_TASKS_INITIAL_STATE,
    HUB_STATS_INITIAL_STATE,
    SERVO_CALIBRATION_INITIAL_STATE
} from './reducers';

export const INITIAL_STATE: IState = {
    bluetoothAvailability: BLUETOOTH_AVAILABILITY_INITIAL_STATE,
    controllers: CONTROLLERS_INITIAL_STATE,
    controllerInput: CONTROLLER_INPUT_INITIAL_STATE,
    controllerSettings: CONTROLLER_SETTINGS_INITIAL_STATE,
    controlSchemes: CONTROL_SCHEMES_INITIAL_STATE,
    hubs: HUBS_INITIAL_STATE,
    hubStats: HUB_STATS_INITIAL_STATE,
    attachedIos: ATTACHED_IOS_INITIAL_STATE,
    attachedIoProps: ATTACHED_IO_PROPS_INITIAL_STATE,
    attachedIoModes: ATTACHED_IO_MODES_INITIAL_STATE,
    attachedIoPortModeInfo: ATTACHED_IO_PORT_MODE_INFO_INITIAL_STATE,
    hubPortTasks: HUB_PORT_TASKS_INITIAL_STATE,
    hubEditFormActiveSaves: HUB_EDIT_FORM_ACTIVE_SAVES_INITIAL_STATE,
    servoCalibrationTaskState: SERVO_CALIBRATION_INITIAL_STATE,
    router: RouterState.Full,
};
